import 'dotenv/config'; 
export const limit = {
    windowMs : 1 * 60 * 1000,
    limit : 100
}

// Env exports
export const redisUrl = process.env.UPSTASH_REDIS_REST_URL
export const redisToken = process.env.UPSTASH_REDIS_REST_TOKEN
export const crustUrl = process.env.CRUST_URL
export const crustToken = process.env.CRUST_TOKEN
export const crustXVersion = process.env.CRUST_X_VERSION

console.log(crustUrl)

// Types
export type filterVal = string | number | string[] | number[] | null;
export type filter = {
    key : string,
    value : filterVal
}

type industryType = {
    industry : string,
    business_model : string[],
    target_personas : string[]
}


export const industries : industryType[] = [
  {"industry":"abrasives-and-nonmetallic-minerals-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"accessible-architecture-and-design","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"accessible-hardware-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"accommodation-and-food-services","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"accounting","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"administration-of-justice","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"administrative-and-support-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"advertising-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"agricultural-chemical-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"agriculture,-construction,-mining-machinery-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"air,-water,-and-waste-program-management","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"airlines-and-aviation","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"alternative-dispute-resolution","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"alternative-medicine","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"ambulance-services","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"amusement-parks-and-arcades","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"animacje","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"animation-and-post-production","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"apparel-&-fashion","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"apparel-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"appliances,-electrical,-and-electronics-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"architectural-and-structural-metal-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"architecture-and-planning","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"architektura-i-planowanie","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"armed-forces","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"artificial-rubber-and-synthetic-fiber-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"artists-and-writers","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"arts-&-crafts","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"audio-and-video-equipment-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"automation-machinery-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"automotive","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"aviation-&-aerospace","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"aviation-and-aerospace-component-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"baked-goods-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"banking","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"bars,-taverns,-and-nightclubs","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"bed-and-breakfasts,-hostels,-homestays","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"beverage-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"biomass-electric-power-generation","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"biotechnology","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"biotechnology-research","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"blockchain-services","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"blogs","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"boilers,-tanks,-and-shipping-container-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"book-publishing","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"book-and-periodical-publishing","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"breweries","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"broadcast-media-production-and-distribution","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"budowa-statków","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"budownictwo","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"building-construction","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"building-equipment-contractors","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"building-finishing-contractors","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"building-materials","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"building-structure-and-exterior-contractors","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"business-consulting-and-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"business-content","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"business-intelligence-platforms","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"business-supplies-&-equipment","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"cable-and-satellite-programming","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"capital-markets","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"chemical-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"chemical-raw-materials-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"child-day-care-services","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"circuses-and-magic-shows","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"civic-and-social-organizations","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"civil-engineering","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"claims-adjusting,-actuarial-services","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"clay-and-refractory-products-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"climate-data-and-analytics","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"climate-technology-product-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"commercial-and-industrial-equipment-rental","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"commercial-and-industrial-machinery-maintenance","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"commercial-and-service-industry-machinery-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"communications-equipment-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"community-development-and-urban-planning","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"community-services","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"computer-games","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"computer-hardware","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"computer-hardware-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"computer-networking","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"computer-networking-products","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"computer-and-network-security","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"computers-and-electronics-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"construction","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"construction-hardware-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"consumer-goods","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"consumer-services","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"cosmetics","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"cosmetology-and-barber-schools","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"courts-of-law","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"credit-intermediation","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"cutlery-and-handtool-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"czas-wolny,-podróże-i-turystyka","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"dairy","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"dairy-product-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"data-infrastructure-and-analytics","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"data-security-software-products","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"defense-and-space-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"design","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"design-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"desktop-computing-software-products","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"digital-accessibility-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"e-learning-providers","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"e-learning","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"education","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"education-administration-programs","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"education-management","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"electric-lighting-equipment-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"electric-power-generation","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"electric-power-transmission,-control,-and-distribution","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"electrical-equipment-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"electronic-and-precision-equipment-maintenance","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"embedded-software-products","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"emergency-and-relief-services","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"energy-technology","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"engineering-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"engines-and-power-transmission-equipment-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"entertainment","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"entertainment-providers","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"environmental-quality-programs","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"environmental-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"equipment-rental-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"events-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"executive-offices","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"executive-search-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"fabricated-metal-products","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"facilities-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"family-planning-centers","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"farming","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"farming,-ranching,-forestry","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"fashion-accessories-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"filmy,-wideo-i-dźwięk","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"financial-services","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"fine-art","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"fire-protection","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"fisheries","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"food-&-beverages","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"food-production","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"food-and-beverage-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"food-and-beverage-retail","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"food-and-beverage-services","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"footwear-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"footwear-and-leather-goods-repair","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"forestry-and-logging","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"fossil-fuel-electric-power-generation","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"freight-and-package-transportation","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"fruit-and-vegetable-preserves-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"fundraising","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"furniture","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"furniture-and-home-furnishings-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"gambling-facilities-and-casinos","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"geothermal-electric-power-generation","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"glass,-ceramics-and-concrete-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"golf-courses-and-country-clubs","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"government-administration","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"government-relations","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"government-relations-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"graphic-design","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"ground-passenger-transportation","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"hvac-and-refrigeration-equipment-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"handel-detaliczny","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"health-and-human-services","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"health,-wellness-&-fitness","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"higher-education","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"highway,-street,-and-bridge-construction","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"holding-companies","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"home-health-care-services","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"horticulture","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"hospitality","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"hospitals-and-health-care","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"hotelarstwo","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"hotels-and-motels","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"household-services","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"housing-and-community-development","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"human-resources","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"human-resources-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"hydroelectric-power-generation","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"it-services-and-it-consulting","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"it-system-custom-software-development","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"it-system-data-services","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"it-system-design-services","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"it-system-installation-and-disposal","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"it-system-operations-and-maintenance","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"it-system-testing-and-evaluation","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"it-system-training-and-support","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"import-&-export","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"import-i-eksport-—-handel-hurtowy","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"individual-and-family-services","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"industrial-machinery-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"industry-associations","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"information-services","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"information-technology-&-services","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"insurance","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"insurance-agencies-and-brokerages","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"insurance-and-employee-benefit-funds","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"interior-design","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"international-affairs","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"international-trade-and-development","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"internet-marketplace-platforms","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"internet-news","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"internet-publishing","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"interurban-and-rural-bus-services","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"investment-advice","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"investment-banking","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"investment-management","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"janitorial-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"kadry-i-rekrutacja","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"konsulting-biznesowy-i-usługi","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"księgowość","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"laboratoria-medyczne-i-diagnostyczne","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"landscaping-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"language-schools","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"laundry-and-drycleaning-services","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"law-enforcement","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"law-practice","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"leasing-non-residential-real-estate","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"leather-product-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"legal-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"leisure,-travel-&-tourism","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"libraries","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"lime-and-gypsum-products-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"loan-brokers","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"luxury-goods-&-jewelry","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"machinery-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"maritime-transportation","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"market-research","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"marketing-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"mattress-and-blinds-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"mechanical-or-industrial-engineering","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"media-production","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"media-and-telecommunications","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"media-i-telekomunikacja","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"media-internetowe","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"medical-device","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"medical-equipment-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"medical-practices","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"medical-and-diagnostic-laboratories","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"mental-health-care","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"metal-valve,-ball,-and-roller-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"metalworking-machinery-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"military-and-international-affairs","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"mining","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"mobile-computing-software-products","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"mobile-food-services","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"mobile-gaming-apps","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"motor-vehicle-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"motor-vehicle-parts-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"movies-and-sound-recording","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"movies,-videos,-and-sound","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"museums,-historical-sites,-and-zoos","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"music","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"musicians","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"muzea","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"nanotechnology-research","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"natural-gas-distribution","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"natural-gas-extraction","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"newspaper-publishing","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"non-profit-organization-management","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"non-profit-organizations","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"nonresidential-building-construction","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"nuclear-electric-power-generation","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"nursing-homes-and-residential-care-facilities","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"odzież-i-moda","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"odzież-i-moda-—-sprzedaż-detaliczna","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"office-furniture-and-fixtures-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"oil-extraction","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"oil-and-gas","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"oil,-gas,-and-mining","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"online-audio-and-video-media","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"operations-consulting","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"organizacja-podróży","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"organizacje-non-profit","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"organizacje-rządowe","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"organizacje-zawodowe","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"outsourcing-and-offshoring-consulting","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"outsourcing/offshoring","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"packaging-&-containers","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"packaging-and-containers-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"paint,-coating,-and-adhesive-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"paper-&-forest-products","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"paper-and-forest-product-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"parts-distribution","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"performing-arts","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"performing-arts-and-spectator-sports","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"periodical-publishing","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"personal-care-product-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"personal-care-services","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"personal-and-laundry-services","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"pet-services","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"pharmaceutical-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"philanthropic-fundraising-services","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"philanthropy","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"photography","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"physical,-occupational-and-speech-therapists","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"physicians","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"plastics-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"plastics-and-rubber-product-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"political-organizations","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"posiłki-i-napoje","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"praktyki-prawnicze","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"primary-metal-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"primary-and-secondary-education","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"printing-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"produkcja","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"produkcja-i-dystrybucja-mass-mediów","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"produkcja-maszyn-przemysłowych","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"produkcja-medialna","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"produkcja-opakowań-i-pojemników","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"produkcja-półprzewodników","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"produkcja-urządzeń-elektrycznych-i-elektronicznych","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"produkcja-wyrobów-farmaceutycznych","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"produkcja-środków-higieny-osobistej","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"professional-organizations","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"professional-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"professional-training-and-coaching","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"program-development","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"programy-zarządzania-edukacją","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"projektowanie","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"projektowanie-graficzne","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"public-assistance-programs","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"public-health","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"public-policy","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"public-policy-offices","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"public-relations-and-communications-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"public-safety","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"public-works","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"racetracks","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"radio-and-television-broadcasting","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"railroad-equipment-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"ranching","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"ranching-and-fisheries","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"real-estate","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"real-estate-agents-and-brokers","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"real-estate-and-equipment-rental-services","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"recreational-facilities","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"religious-institutions","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"renewable-energy-equipment-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"renewable-energy-power-generation","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"renewable-energy-semiconductor-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"renewables-&-environment","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"repair-and-maintenance","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"research","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"research-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"residential-building-construction","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"restauracje","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"restaurants","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"retail","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"retail-apparel-and-fashion","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"retail-appliances,-electrical,-and-electronic-equipment","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"retail-art-supplies","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"retail-books-and-printed-news","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"retail-building-materials-and-garden-equipment","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"retail-furniture-and-home-furnishings","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"retail-groceries","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"retail-health-and-personal-care-products","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"retail-luxury-goods-and-jewelry","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"retail-motor-vehicles","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"retail-office-equipment","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"retail-pharmacies","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"retail-recyclable-materials-&-used-merchandise","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"reupholstery-and-furniture-repair","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"robot-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"robotics-engineering","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"rolnictwo,-hodowla-zwierząt,-leśnictwo","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"rubber-products-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"school-and-employee-bus-services","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"securities-and-commodity-exchanges","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"security-guards-and-patrol-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"security-systems-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"security-and-investigations","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"semiconductor-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"services-for-renewable-energy","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"services-for-the-elderly-and-disabled","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"sheet-music-publishing","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"shipbuilding","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"skiing-facilities","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"social-networking-platforms","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"software-development","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"solar-electric-power-generation","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"space-research-and-technology","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"specialty-trade-contractors","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"spectator-sports","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"sporting-goods","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"sporting-goods-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"sports-teams-and-clubs","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"sports-and-recreation-instruction","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"sporty-widowiskowe","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"spring-and-wire-product-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"sprzedaż-detaliczna-dóbr-luksusowych-i-biżuterii","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"sprzedaż-hurtowa-materiałów-budowlanych","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"sprzedaż-hurtowa-produktów-papierniczych","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"staffing-and-recruiting","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"steam-and-air-conditioning-supply","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"strategic-management-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"subdivision-of-land","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"sugar-and-confectionery-product-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"surveying-and-mapping-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"szkolenia-zawodowe-i-coaching","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"szkolnictwo-podstawowe-i-średnie","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"szkolnictwo-wyższe","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"szkoły-językowe","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"taxi-and-limousine-services","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"technical-and-vocational-training","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"technologia,-informacja-i-internet","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"technologia,-informacja-i-media","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"technologie-i-usługi-informatyczne","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"technology,-information-and-internet","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"technology,-information-and-media","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"telecommunications","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"telekomunikacja","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"temporary-help-services","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"textile-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"think-tanks","business_model":["Government & Non-Profit"],"target_personas":["Executive Director","Policy Director","Program Manager"]},
  {"industry":"tobacco","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"tobacco-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"translation-and-localization","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"transportation-equipment-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"transportation,-logistics,-supply-chain-and-storage","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"transportation/trucking/railroad","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"travel-arrangements","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"truck-transportation","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"tworzenie-oprogramowania","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"tłumaczenia-i-lokalizacja","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"ubezpieczenia","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"urban-transit-services","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"usługi-blockchain","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"usługi-badawcze","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"usługi-dla-osób-indywidualnych-i-rodzin","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"usługi-dla-zwierząt","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"usługi-drukarskie","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"usługi-finansowe","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"usługi-i-doradztwo-informatyczne","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"usługi-informacyjne","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"usługi-inżynieryjne","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"usługi-konsumenckie","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"usługi-marketingowe","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"usługi-projektowe","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"usługi-reklamowe","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"utilities","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"utility-system-construction","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"vehicle-repair-and-maintenance","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"venture-capital-and-private-equity-principals","business_model":["Finance / Institutional"],"target_personas":["CFO","VP Finance","Chief Risk Officer"]},
  {"industry":"veterinary","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"veterinary-services","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"vocational-rehabilitation-services","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"warehousing","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"warehousing-and-storage","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"waste-collection","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"waste-treatment-and-disposal","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"water-supply-and-irrigation-systems","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"water,-waste,-steam,-and-air-conditioning-services","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"wellness-and-fitness-services","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"wholesale","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"wholesale-alcoholic-beverages","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"wholesale-apparel-and-sewing-supplies","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"wholesale-appliances,-electrical,-and-electronics","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"wholesale-building-materials","business_model":["Real Estate & Construction"],"target_personas":["VP Construction","Project Executive","Real Estate Director"]},
  {"industry":"wholesale-chemical-and-allied-products","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"wholesale-computer-equipment","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"wholesale-drugs-and-sundries","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"wholesale-food-and-beverage","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"wholesale-footwear","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"wholesale-furniture-and-home-furnishings","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"wholesale-hardware,-plumbing,-heating-equipment","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"wholesale-import-and-export","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"wholesale-luxury-goods-and-jewelry","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"wholesale-machinery","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"wholesale-metals-and-minerals","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"wholesale-motor-vehicles-and-parts","business_model":["Transportation & Logistics"],"target_personas":["VP Logistics","Fleet Manager","Supply Chain Director"]},
  {"industry":"wholesale-paper-products","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"wholesale-petroleum-and-petroleum-products","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"wholesale-photography-equipment-and-supplies","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"wholesale-raw-farm-products","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"wholesale-recyclable-materials","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"wina-i-napoje-alkoholowe","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"wind-electric-power-generation","business_model":["Agriculture & Energy"],"target_personas":["VP Operations","Site Manager","EHS Director"]},
  {"industry":"wine-&-spirits","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"wineries","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"wireless-services","business_model":["B2B Tech / SaaS"],"target_personas":["CIO","CTO","VP Engineering","Head of IT"]},
  {"industry":"women's-handbag-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"wood-product-manufacturing","business_model":["Manufacturing / Industrial"],"target_personas":["VP Operations","Plant Manager","Supply Chain Director"]},
  {"industry":"writing-and-editing","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"wykształcenie","business_model":["Education"],"target_personas":["Provost","Dean","Director of Admissions"]},
  {"industry":"zarządzanie-strategiczne","business_model":["B2B Services"],"target_personas":["CEO","COO","Managing Partner","VP Operations"]},
  {"industry":"zdrowie-i-kondycja-fizyczna","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"zdrowie,-wellness-i-fitness","business_model":["Healthcare / Medical"],"target_personas":["Chief Medical Officer","Hospital Administrator","VP Clinical Operations"]},
  {"industry":"zoos-and-botanical-gardens","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]},
  {"industry":"żywność-i-napoje","business_model":["B2C / Consumer"],"target_personas":["CMO","VP Retail","E-commerce Director","Brand Manager"]}
]